// packages/admin/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { type EntityModel, EntityModelStatus } from "@kitledger/core/entities";
import { type TransactionModel, TransactionModelStatus } from "@kitledger/core/transactions";
import { type UnitModel, UnitModelStatus } from "@kitledger/core/units";
import type { BaseForm } from "@kitledger/core/forms";
import type { AdminUIOptions } from "../shared";

const transactions = ref<TransactionModel[]>([]);
const entities = ref<EntityModel[]>([]);
const units = ref<UnitModel[]>([]);
const allForms = ref<BaseForm[]>([]);
const config = ref<AdminUIOptions | null>(null);

function getFormsForModel(modelId: string) {
	return allForms.value.filter((f) => f.modelRefId === modelId);
}

function getStatusBadgeClass(status?: TransactionModelStatus | EntityModelStatus | UnitModelStatus) {
	// Cast to string to satisfy TypeScript's overlap check for Enums
	return !status || (status as unknown as string) === "ACTIVE"
		? "badge-success text-success-content"
		: "badge-warning text-warning-content";
}

onMounted(() => {
	const winConfig = (window as any).KITLEDGER_CONFIG;

	if (!winConfig) {
		console.warn("Kitledger config not found on window");
		return;
	}

	config.value = winConfig;

	Promise.all([
		fetch(`${winConfig.serverPath}/transactions/models`).then((res) => res.json()),
		fetch(`${winConfig.serverPath}/entities/models`).then((res) => res.json()),
		fetch(`${winConfig.serverPath}/units/models`).then((res) => res.json()),

		fetch(`${winConfig.serverPath}/transactions/forms`)
			.then((res) => res.json())
			.catch(() => []),
		fetch(`${winConfig.serverPath}/entities/forms`)
			.then((res) => res.json())
			.catch(() => []),
		fetch(`${winConfig.serverPath}/units/forms`)
			.then((res) => res.json())
			.catch(() => []),
	])
		.then(([txModels, entityModels, unitModels, txForms, entityForms, unitForms]) => {
			transactions.value = txModels;
			entities.value = entityModels;
			units.value = unitModels;
			allForms.value = [...txForms, ...entityForms, ...unitForms];
		})
		.catch(console.error);
});
</script>

<template>
	<div class="p-8 max-w-5xl mx-auto font-sans bg-base-100 min-h-screen text-base-content">
		<div v-if="!config" role="alert" class="alert alert-error">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				class="stroke-current shrink-0 h-6 w-6"
				fill="none"
				viewBox="0 0 24 24"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
				/>
			</svg>
			<span>No Configuration Found. Please check KITLEDGER_CONFIG.</span>
		</div>

		<div v-else>
			<header class="mb-10 pb-6 border-b border-base-300">
				<h1 class="text-4xl font-bold tracking-tight">Kitledger Admin</h1>
				<p class="text-base-content/60 mt-1 font-mono text-sm">System Configuration & Schema</p>
			</header>

			<section class="mb-12">
				<h2 class="text-xl font-bold mb-6 flex items-center gap-3">
					Transaction Models
					<span class="badge badge-neutral font-mono">{{ transactions.length }}</span>
				</h2>

				<div class="flex flex-col gap-4">
					<div
						v-for="model in transactions"
						:key="model.refId"
						class="card card-sm bg-base-100 border border-base-300 shadow-sm hover:shadow-md transition-all"
					>
						<div class="card-body p-5">
							<div class="flex justify-between items-start mb-4 border-b border-base-200 pb-3">
								<div>
									<h3 class="card-title text-lg text-primary mb-1">{{ model.name }}</h3>
									<span class="badge badge-sm badge-ghost font-mono text-xs text-base-content/60">{{
										model.refId
									}}</span>
								</div>
								<div
									class="badge badge-sm font-bold tracking-wide uppercase"
									:class="getStatusBadgeClass(model.status)"
								>
									{{ model.status || "ACTIVE" }}
								</div>
							</div>

							<div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm">
								<div>
									<h4
										class="font-bold border-b border-base-300 pb-1 mb-3 text-xs uppercase tracking-wider"
									>
										Fields ({{ model.fields?.length || 0 }})
									</h4>
									<ul class="space-y-2">
										<li
											v-for="f in model.fields"
											:key="f.refId"
											class="flex items-center justify-between group"
										>
											<span class="group-hover:text-primary transition-colors">{{ f.name }}</span>
											<div class="flex items-center gap-2">
												<span
													v-if="f.required"
													class="badge badge-xs badge-error badge-outline font-bold"
													>REQ</span
												>
												<span
													class="font-mono text-xs text-base-content/50 bg-base-200 px-1 rounded"
													>{{ f.type }}</span
												>
											</div>
										</li>
									</ul>
								</div>
								<div>
									<h4
										class="font-bold border-b border-base-300 pb-1 mb-3 text-xs uppercase tracking-wider"
									>
										Forms ({{ getFormsForModel(model.refId).length }})
									</h4>
									<ul v-if="getFormsForModel(model.refId).length > 0" class="space-y-2">
										<li
											v-for="form in getFormsForModel(model.refId)"
											:key="form.refId"
											class="flex flex-col p-2 bg-base-200/50 rounded-box border border-base-200 hover:border-primary/50 transition-colors"
										>
											<span class="font-medium">{{ form.name }}</span>
											<code class="text-[10px] text-base-content/50 font-mono">{{
												form.refId
											}}</code>
										</li>
									</ul>
									<div v-else class="alert alert-soft alert-sm text-xs py-2 opacity-70">
										No forms defined.
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section class="mb-12">
				<h2 class="text-xl font-bold mb-6 flex items-center gap-3">
					Entity Models
					<span class="badge badge-neutral font-mono">{{ entities.length }}</span>
				</h2>
				<div class="flex flex-col gap-4">
					<div
						v-for="model in entities"
						:key="model.refId"
						class="card card-sm bg-base-100 border border-base-300 shadow-sm hover:shadow-md transition-all"
					>
						<div class="card-body p-5">
							<div class="flex justify-between items-start mb-4 border-b border-base-200 pb-3">
								<div>
									<h3 class="card-title text-lg text-primary mb-1">{{ model.name }}</h3>
									<span class="badge badge-sm badge-ghost font-mono text-xs text-base-content/60">{{
										model.refId
									}}</span>
								</div>
								<div
									class="badge badge-sm font-bold tracking-wide uppercase"
									:class="getStatusBadgeClass(model.status)"
								>
									{{ model.status || "ACTIVE" }}
								</div>
							</div>
							<div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm">
								<div>
									<h4
										class="font-bold border-b border-base-300 pb-1 mb-3 text-xs uppercase tracking-wider"
									>
										Fields ({{ model.fields?.length || 0 }})
									</h4>
									<ul class="space-y-2">
										<li
											v-for="f in model.fields"
											:key="f.refId"
											class="flex items-center justify-between group"
										>
											<span class="group-hover:text-primary transition-colors">{{ f.name }}</span>
											<div class="flex items-center gap-2">
												<span
													v-if="f.required"
													class="badge badge-xs badge-error badge-outline font-bold"
													>REQ</span
												>
												<span
													class="font-mono text-xs text-base-content/50 bg-base-200 px-1 rounded"
													>{{ f.type }}</span
												>
											</div>
										</li>
									</ul>
								</div>
								<div>
									<h4
										class="font-bold border-b border-base-300 pb-1 mb-3 text-xs uppercase tracking-wider"
									>
										Forms ({{ getFormsForModel(model.refId).length }})
									</h4>
									<ul v-if="getFormsForModel(model.refId).length > 0" class="space-y-2">
										<li
											v-for="form in getFormsForModel(model.refId)"
											:key="form.refId"
											class="flex flex-col p-2 bg-base-200/50 rounded-box border border-base-200 hover:border-primary/50 transition-colors"
										>
											<span class="font-medium">{{ form.name }}</span>
											<code class="text-[10px] text-base-content/50 font-mono">{{
												form.refId
											}}</code>
										</li>
									</ul>
									<div v-else class="alert alert-soft alert-sm text-xs py-2 opacity-70">
										No forms defined.
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section class="mb-12">
				<h2 class="text-xl font-bold mb-6 flex items-center gap-3">
					Unit Models
					<span class="badge badge-neutral font-mono">{{ units.length }}</span>
				</h2>
				<div class="flex flex-col gap-4">
					<div
						v-for="model in units"
						:key="model.refId"
						class="card card-sm bg-base-100 border border-base-300 shadow-sm hover:shadow-md transition-all"
					>
						<div class="card-body p-5">
							<div class="flex justify-between items-start mb-4 border-b border-base-200 pb-3">
								<div>
									<h3 class="card-title text-lg text-primary mb-1">{{ model.name }}</h3>
									<span class="badge badge-sm badge-ghost font-mono text-xs text-base-content/60">{{
										model.refId
									}}</span>
								</div>
								<div
									class="badge badge-sm font-bold tracking-wide uppercase"
									:class="getStatusBadgeClass(model.status)"
								>
									{{ model.status || "ACTIVE" }}
								</div>
							</div>
							<div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm">
								<div>
									<h4
										class="font-bold border-b border-base-300 pb-1 mb-3 text-xs uppercase tracking-wider"
									>
										Fields ({{ model.fields?.length || 0 }})
									</h4>
									<ul class="space-y-2">
										<li
											v-for="f in model.fields"
											:key="f.refId"
											class="flex items-center justify-between group"
										>
											<span class="group-hover:text-primary transition-colors">{{ f.name }}</span>
											<div class="flex items-center gap-2">
												<span
													v-if="f.required"
													class="badge badge-xs badge-error badge-outline font-bold"
													>REQ</span
												>
												<span
													class="font-mono text-xs text-base-content/50 bg-base-200 px-1 rounded"
													>{{ f.type }}</span
												>
											</div>
										</li>
									</ul>
								</div>
								<div>
									<h4
										class="font-bold border-b border-base-300 pb-1 mb-3 text-xs uppercase tracking-wider"
									>
										Forms ({{ getFormsForModel(model.refId).length }})
									</h4>
									<ul v-if="getFormsForModel(model.refId).length > 0" class="space-y-2">
										<li
											v-for="form in getFormsForModel(model.refId)"
											:key="form.refId"
											class="flex flex-col p-2 bg-base-200/50 rounded-box border border-base-200 hover:border-primary/50 transition-colors"
										>
											<span class="font-medium">{{ form.name }}</span>
											<code class="text-[10px] text-base-content/50 font-mono">{{
												form.refId
											}}</code>
										</li>
									</ul>
									<div v-else class="alert alert-soft alert-sm text-xs py-2 opacity-70">
										No forms defined.
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</template>

// packages/admin/src/App.tsx
import type { EntityModel } from "@kitledger/core/entities";
import type { BaseForm } from "@kitledger/core/forms";
import type { TransactionModel } from "@kitledger/core/transactions";
import type { UnitModel } from "@kitledger/core/units";

import { useEffect, useState } from "react";

import type { AdminUIOptions } from "../shared";

function App() {
	const [transactions, setTransactions] = useState<TransactionModel[]>([]);
	const [entities, setEntities] = useState<EntityModel[]>([]);
	const [units, setUnits] = useState<UnitModel[]>([]);
	const [allForms, setAllForms] = useState<BaseForm[]>([]);

	const config: AdminUIOptions = (window as any).KITLEDGER_CONFIG;

	useEffect(() => {
		if (!config) return;

		// Fetch all data in parallel
		Promise.all([
			// Models
			fetch(`${config.serverPath}/transactions/models`).then((res) => res.json()),
			fetch(`${config.serverPath}/entities/models`).then((res) => res.json()),
			fetch(`${config.serverPath}/units/models`).then((res) => res.json()),

			// Forms (Namespace specific)
			fetch(`${config.serverPath}/transactions/forms`)
				.then((res) => res.json())
				.catch(() => []),
			fetch(`${config.serverPath}/entities/forms`)
				.then((res) => res.json())
				.catch(() => []),
			fetch(`${config.serverPath}/units/forms`)
				.then((res) => res.json())
				.catch(() => []),
		])
			.then(([txModels, entityModels, unitModels, txForms, entityForms, unitForms]) => {
				setTransactions(txModels);
				setEntities(entityModels);
				setUnits(unitModels);
				// Combine all forms into one array for easier lookup by modelRefId
				setAllForms([...txForms, ...entityForms, ...unitForms]);
			})
			.catch(console.error);
	}, [config]);

	if (!config) return <div className="p-4">No Config Found</div>;

	return (
		<div className="p-8 max-w-4xl mx-auto font-sans text-gray-800">
			<header className="mb-8 pb-4 border-b border-gray-300">
				<h1 className="text-3xl font-bold">Kitledger Admin</h1>
				<p className="text-gray-500">System Configuration</p>
			</header>

			{/* Transactions Section */}
			<section className="mb-10">
				<h2 className="text-xl font-bold mb-4 flex items-center">
					Transaction Models
					<span className="ml-2 text-sm bg-gray-200 px-2 py-0.5 rounded-full text-gray-700">
						{transactions.length}
					</span>
				</h2>
				<div className="space-y-4">
					{transactions.map((model) => (
						<ModelRow key={model.refId} model={model} forms={allForms} />
					))}
				</div>
			</section>

			{/* Entities Section */}
			<section className="mb-10">
				<h2 className="text-xl font-bold mb-4 flex items-center">
					Entity Models
					<span className="ml-2 text-sm bg-gray-200 px-2 py-0.5 rounded-full text-gray-700">
						{entities.length}
					</span>
				</h2>
				<div className="space-y-4">
					{entities.map((model) => (
						<ModelRow key={model.refId} model={model} forms={allForms} />
					))}
				</div>
			</section>

			{/* Units Section */}
			<section>
				<h2 className="text-xl font-bold mb-4 flex items-center">
					Unit Models
					<span className="ml-2 text-sm bg-gray-200 px-2 py-0.5 rounded-full text-gray-700">
						{units.length}
					</span>
				</h2>
				<div className="space-y-4">
					{units.map((model) => (
						<ModelRow key={model.refId} model={model} forms={allForms} />
					))}
				</div>
			</section>
		</div>
	);
}

// --- Simple Sub-Component ---

function ModelRow({ model, forms }: { model: any; forms: BaseForm[] }) {
	// Find forms that belong to this specific model
	const relatedForms = forms.filter((f) => f.modelRefId === model.refId);

	return (
		<div className="border border-gray-300 rounded p-4 bg-white">
			<div className="flex justify-between items-start mb-4">
				<div>
					<h3 className="text-lg font-bold text-blue-700">{model.name}</h3>
					<code className="text-xs bg-gray-100 px-1 py-0.5 rounded text-gray-500">{model.refId}</code>
				</div>
				<div className="text-xs font-bold text-green-700 uppercase tracking-wide">
					{model.status || "ACTIVE"}
				</div>
			</div>

			<div className="grid grid-cols-2 gap-8 text-sm">
				{/* Left: Fields */}
				<div>
					<h4 className="font-bold text-gray-900 border-b border-gray-100 pb-1 mb-2">
						Fields ({model.fields?.length || 0})
					</h4>
					<ul className="space-y-1 text-gray-600">
						{model.fields?.map((f: any) => (
							<li key={f.refId} className="flex items-center justify-between">
								<span>{f.name}</span>
								<div className="flex items-center gap-2">
									{f.required && (
										<span className="text-[10px] text-red-600 font-bold border border-red-200 px-1 rounded">
											REQ
										</span>
									)}
									<span className="text-xs text-gray-400 font-mono">{f.type}</span>
								</div>
							</li>
						))}
					</ul>
				</div>

				{/* Right: Forms */}
				<div>
					<h4 className="font-bold text-gray-900 border-b border-gray-100 pb-1 mb-2">
						Forms ({relatedForms.length})
					</h4>
					{relatedForms.length > 0 ? (
						<ul className="space-y-1">
							{relatedForms.map((form) => (
								<li
									key={form.refId}
									className="flex flex-col mb-2 p-2 bg-gray-50 rounded border border-gray-100"
								>
									<span className="font-medium text-gray-800">{form.name}</span>
									<code className="text-[10px] text-gray-400">{form.refId}</code>
								</li>
							))}
						</ul>
					) : (
						<p className="text-gray-400 italic">No forms defined.</p>
					)}
				</div>
			</div>
		</div>
	);
}

export default App;
